# Generated by Django 3.2.11 on 2022-02-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_alter_videos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['title']},
        ),
    ]
