# Generated by Django 3.2.11 on 2022-02-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_alter_videos_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
